version: "3.9"

services:
  db:
    image:  postgres:12.11-alpine
    # ports:
    #   - "5438:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT='5432'
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - ./code :/code
    ports:
      - "8010:8010"
    depends_on:
      - db