# Generated by Django 4.0.3 on 2022-06-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_admin_blog_name_remove_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mysite.blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='mysite.category'),
        ),
    ]
